apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-app-dep-metadata
spec:
  selector:
    matchLabels:
      app: frontend-app
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend-app
    spec:
      containers:
      - name: frontend-app
        image: say2imran/frontend_image:v2
        #imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        