apiVersion: apps/v1
kind: Deployment
metadata:
  name: getter-app-dep-metadat
spec:
  selector:
    matchLabels:
      app: getter-app
  replicas: 1
  template:
    metadata:
      labels:
        app: getter-app
    spec:
      containers:
      - name: getter-app
        image: say2imran/getter_image:v2
        #imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8081
        