apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend-app
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: getter-service
spec:
  selector:
    app: getter-app
  ports:
    - protocol: "TCP"
      port: 8081
      targetPort: 8081
  #type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: putter-service
spec:
  selector:
    app: putter-app
  ports:
    - protocol: "TCP"
      port: 8082
      targetPort: 8082
  #type: LoadBalancer
